language: java
jdk:
  - oraclejdk7
  - oraclejdk8
  
before_install:
  - "export DISPLAY=:99.0"
  - "export TERM=dumb"

  - "cd VRL"

install:
    - TERM=dumb ant clean

script:
    - TERM=dumb ant test
