language: java
jdk:
  - oraclejdk7
  - oraclejdk8
  
before_install:
  - "export DISPLAY=:0"
  - "export TERM=dumb"
  - "sh -e /etc/init.d/xvfb start"
  - "cd VRL"

install:
    - TERM=dumb ant clean

script:
    - TERM=dumb ant test
